spring:
  datasource:
    url: jdbc:mysql://database-2.cshxu2jawger.ap-northeast-2.rds.amazonaws.com:3306/hackaton7
    #url : jdbc:mysql://localhost:3306/hackaton7
    username: root  # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: hackaton7 # 비밀번호를 입력해주세요!
    #password : yeojin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000  # 9000번 포트로 실행